steps:
  # Step 1: Build the Docker image
  - name: 'docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops', '.']

  # Step 2: Deploy the container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=gke.yaml
      - --image=gcr.io/$PROJECT_ID/gcpdevops
      - --location=us-central1-c
      - --cluster=gcp-devops-project
      - --namespace=gcp-devops-prod

images:
  - 'gcr.io/$PROJECT_ID/gcpdevops'

options:
  logging: CLOUD_LOGGING_ONLY
